### ISSUE TITLE
原版mekanism转换新mekanism

### ISSUE THREAD

**Issue by koffing123** [sddsd2332/MEK-1.12.2-v10#25]
我自己的模组包本来用的是原版的mekanism但看到你模组我就想换过来，换过来虽然很顺利但是有些机器会有问题以前放置的机器会crash游戏，而且所有机器的auto eject都变成了off, 还有很多机器貌似名字都没有间隔比如说ultimate crushing factory是ultimatecrushingfactory连在一起的， 以下我的crash log: 

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-04-06 23:09:43 PDT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 57, Size: 54
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.func_181617_a(Util.java:531)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IndexOutOfBoundsException: Index: 57, Size: 54
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at net.minecraft.inventory.Container.func_75139_a(Container.java:120)
    at net.minecraft.inventory.Container.func_75141_a(Container.java:519)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1154)
    at net.minecraft.network.play.server.SPacketSetSlot.func_148833_a(SourceFile:30)
    at net.minecraft.network.play.server.SPacketSetSlot.func_148833_a(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.func_181617_a(Util.java:529)
    ... 9 more

**Comment by sddsd2332** [comment]
很明显，你在下载的时候没有看描述，
在原存档转换为该版本的时候，如果已经摆放到地面的精英工厂类型方块，需要重新拆除放置，这是因为转换的过程，原方块会多出两个线程，造成索引错误
auto eject【自动弹出】如果变成off，你可以重新打开
至于名称没有间隔 这是和高版本mek同步的
